version: '2'
services:
  demo_jhipster-app:
    image: demo_jhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://demo_jhipster-mssql:1433;database=demo_jhipster
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  demo_jhipster-mssql:
    extends:
      file: mssql.yml
      service: demo_jhipster-mssql
